# Generated by Django 6.0.4 on 2026-05-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetriKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaman_ms', models.BigIntegerField()),
                ('hiz_kmh', models.FloatField()),
                ('T_bat_C', models.FloatField()),
                ('V_bat_V', models.FloatField()),
                ('kalan_enerji', models.FloatField()),
                ('sunucu_zaman', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['zaman_ms'],
            },
        ),
    ]
