# Generated by Django 6.0.7 on 2026-07-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrikayit',
            name='T_bat_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetrikayit',
            name='V_bat_V',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetrikayit',
            name='hiz_kmh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetrikayit',
            name='kalan_enerji',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
